### ISSUE TITLE
Add mechanism to query for submodules' enabled/disabled status

### ISSUE THREAD

**Issue by MysteriousAges** [ForestryMC/ForestryAPI#14]
MagicBees/MagicBees#63 reveals a weakness in the current setup: there is currently no way to tell which, if any, of the Forestry plugins have been switched off, and thus, which items/blocks are missing or unavailable.

**Comment by CovertJaguar** [comment]
Erm...I'm pretty sure my original implementation had that...

**Comment by CovertJaguar** [comment]
Oh...you mean via the API...nvm
