### ISSUE TITLE
FuelManager hash maps are not populated.

### ISSUE THREAD

**Issue by bloxgate** [ForestryMC/ForestryAPI#15]
I'm trying to get all of the fluids that are considered generatorFuel, however when I run through the HashMap provided by the fluid manager, I get no results. 
This is and example of the code I'm using:
```java
@EventHandler
    public void postinit(FMLPostInitializationEvent event){
    	System.out.println("Fuels:");
    	for(GeneratorFuel fuel: FuelManager.generatorFuel.values()){
    		System.out.println(fuel);
    	}
    }
```
And I'm getting nothing printed out besides the word Fuels.

**Comment by mezz** [comment]
Thanks for the report!
It looks like they're only being added when IC2 is present. I'll make sure they're always added.

**Comment by mezz** [comment]
Fixed here: https://github.com/ForestryMC/ForestryMC/commit/9ade0b8df22c650d918cc909a4ac98ac9e602ff6
It should be working in [the latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/).
