### ISSUE TITLE
HiveFrame bools are not working

### ISSUE THREAD

**Issue by mcenderdragon** [ForestryMC/ForestryAPI#16]
Frames cant be "sealed", "SelfLighted", "SunlightSimulated" or "Hellish" (the boolean values in IHiveFrame).

**Comment by mezz** [comment]
Sorry I overlooked the issues reported here.
This should be fixed in Forestry 4.0. @mcenderdragon can you confirm?

**Comment by mcenderdragon** [comment]
Foerstry 4.0 AT Curse I only get Forestry 3.6.9

**Comment by mezz** [comment]
It's available under "Other Downloads" because it's still Beta
http://www.curse.com/mc-mods/Minecraft/forestry#t1:other-downloads

**Comment by mcenderdragon** [comment]
Yes, it works. This is so gread. Thank you very much.
But I have some questions. 
I have added Frames with (high) production/mutation values. In Alverys (so 4 Frames and more) seem do damage the Bee and "Pristine" turns to "Ignoble". Is there a connection or is this caused by Binnie( for Alvery Frames) or by other values ?
Then is there a posibility to make a Bee with more Alleles, so it is able to produce custom Items ? (I tryed to create a "robotic" bee with defineable products)  
And is there a way to add (via a Frame) one drone to the breeding result (Iam curently stuck at converting an Ibee back to an ItemStack)

**Comment by mezz** [comment]
>seems to harm bee and turn "Pristine" into "Ignoble".

If Production is above 16x, the bees are considered overworked and can become Ignoble.

You can create your own bees more easily using the new API, `BeeManager.beeFactory.createSpecies`
This will return an `IAlleleBeeSpeciesCustom` (which is also `IAlleleSpeciesCustom` so check that file too) which has simple methods for adding products, temperature requirements, etc.

Frames are `IBeeModifier`s, not `IBeeListener`s, so adding a breeding result with a frame is not really supported. You could technically do it but it would probably be hacky and might not always work right.

This method will let you get an ItemStack from an `IBee` (which is an `IIndividual`).
It's defined in `ISpeciesRoot`.
```java
BeeManager.beeRoot.getMemberStack(bee, EnumBeeType.DRONE.ordinal());
```

**Comment by mcenderdragon** [comment]
Thank you very much.
