### ISSUE TITLE
implememt listRecipes(), removeRecipe() in RecipesManagers

### ISSUE THREAD

**Issue by Voidi** [ForestryMC/ForestryAPI#9]
Would it be possible to implement functions doing this for all machines?
I'm working on MineTweaker/ModTweaker integration, and these functions like for other mods, would nice to have.

Greetings Tobias

**Comment by mezz** [comment]
@Voidi this has been fully implemented in the latest unstable build and will be in version 4.1.0. 

All the Recipe Managers are [`ICraftingProvider`](https://github.com/ForestryMC/ForestryAPI/blob/master/forestry/api/recipes/ICraftingProvider.java)s which provides `addRecipe`, `removeRecipe`, and `recipes()` (gets all the recipes).

**Comment by Voidi** [comment]
Thanks; it looks like this makes it much easier in Modtweaker.
As this breaks our current code for Forestry 4, are there more breaking changes coming, that we should wait for?

**Comment by mezz** [comment]
I will avoid breaking the API, but I will probably change internal stuff
around. If you need something to be added to the API please let me know and
I can add it soon. I want to avoid breaking your code in the future.

**Comment by mezz** [comment]
@Voidi I am going to release Forestry 4.1.0 soon with these changes. I will see if I can do a PR to update Modtweaker, I feel bad breaking it so soon after it was updated.
